<?php
/**
 * OrderV2
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Keap\Core\V2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Keap API
 *
 * Keap Public API Documentation
 *
 * The version of the OpenAPI document: v2
 * Contact: api.keap@thryv.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Keap\Core\V2\Model;

use \ArrayAccess;
use \Keap\Core\V2\ObjectSerializer;

/**
 * OrderV2 Class Doc Comment
 *
 * @category Class
 * @package  Keap\Core\V2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class OrderV2 implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'OrderV2';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'title' => 'string',
        'status' => 'string',
        'total' => '\Keap\Core\V2\Model\CurrencyValue',
        'contact' => '\Keap\Core\V2\Model\BasicContact',
        'notes' => 'string',
        'terms' => 'string',
        'order_type' => 'string',
        'source_type' => 'string',
        'creation_time' => '\DateTime',
        'modification_time' => '\DateTime',
        'order_time' => '\DateTime',
        'lead_affiliate_id' => 'string',
        'sales_affiliate_id' => 'string',
        'total_paid' => '\Keap\Core\V2\Model\CurrencyValue',
        'total_due' => '\Keap\Core\V2\Model\CurrencyValue',
        'shipping_information' => '\Keap\Core\V2\Model\ShippingInformation',
        'refund_total' => '\Keap\Core\V2\Model\CurrencyValue',
        'allow_payment' => 'bool',
        'allow_paypal' => 'bool',
        'order_items' => '\Keap\Core\V2\Model\OrderItem[]',
        'payment_plan' => '\Keap\Core\V2\Model\PaymentPlan',
        'invoice_number' => 'string',
        'files' => '\Keap\Core\V2\Model\InvoiceFile[]',
        'credit_status' => 'string',
        'promo_code' => 'string',
        'refund_status' => 'string',
        'synced' => 'bool',
        'invoice_id' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'title' => null,
        'status' => null,
        'total' => null,
        'contact' => null,
        'notes' => null,
        'terms' => null,
        'order_type' => null,
        'source_type' => null,
        'creation_time' => 'date-time',
        'modification_time' => 'date-time',
        'order_time' => 'date-time',
        'lead_affiliate_id' => null,
        'sales_affiliate_id' => null,
        'total_paid' => null,
        'total_due' => null,
        'shipping_information' => null,
        'refund_total' => null,
        'allow_payment' => null,
        'allow_paypal' => null,
        'order_items' => null,
        'payment_plan' => null,
        'invoice_number' => null,
        'files' => null,
        'credit_status' => null,
        'promo_code' => null,
        'refund_status' => null,
        'synced' => null,
        'invoice_id' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'title' => false,
        'status' => false,
        'total' => false,
        'contact' => false,
        'notes' => false,
        'terms' => false,
        'order_type' => false,
        'source_type' => false,
        'creation_time' => false,
        'modification_time' => false,
        'order_time' => false,
        'lead_affiliate_id' => false,
        'sales_affiliate_id' => false,
        'total_paid' => false,
        'total_due' => false,
        'shipping_information' => false,
        'refund_total' => false,
        'allow_payment' => false,
        'allow_paypal' => false,
        'order_items' => false,
        'payment_plan' => false,
        'invoice_number' => false,
        'files' => false,
        'credit_status' => false,
        'promo_code' => false,
        'refund_status' => false,
        'synced' => false,
        'invoice_id' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'title' => 'title',
        'status' => 'status',
        'total' => 'total',
        'contact' => 'contact',
        'notes' => 'notes',
        'terms' => 'terms',
        'order_type' => 'order_type',
        'source_type' => 'source_type',
        'creation_time' => 'creation_time',
        'modification_time' => 'modification_time',
        'order_time' => 'order_time',
        'lead_affiliate_id' => 'lead_affiliate_id',
        'sales_affiliate_id' => 'sales_affiliate_id',
        'total_paid' => 'total_paid',
        'total_due' => 'total_due',
        'shipping_information' => 'shipping_information',
        'refund_total' => 'refund_total',
        'allow_payment' => 'allow_payment',
        'allow_paypal' => 'allow_paypal',
        'order_items' => 'order_items',
        'payment_plan' => 'payment_plan',
        'invoice_number' => 'invoice_number',
        'files' => 'files',
        'credit_status' => 'credit_status',
        'promo_code' => 'promo_code',
        'refund_status' => 'refund_status',
        'synced' => 'synced',
        'invoice_id' => 'invoice_id'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'title' => 'setTitle',
        'status' => 'setStatus',
        'total' => 'setTotal',
        'contact' => 'setContact',
        'notes' => 'setNotes',
        'terms' => 'setTerms',
        'order_type' => 'setOrderType',
        'source_type' => 'setSourceType',
        'creation_time' => 'setCreationTime',
        'modification_time' => 'setModificationTime',
        'order_time' => 'setOrderTime',
        'lead_affiliate_id' => 'setLeadAffiliateId',
        'sales_affiliate_id' => 'setSalesAffiliateId',
        'total_paid' => 'setTotalPaid',
        'total_due' => 'setTotalDue',
        'shipping_information' => 'setShippingInformation',
        'refund_total' => 'setRefundTotal',
        'allow_payment' => 'setAllowPayment',
        'allow_paypal' => 'setAllowPaypal',
        'order_items' => 'setOrderItems',
        'payment_plan' => 'setPaymentPlan',
        'invoice_number' => 'setInvoiceNumber',
        'files' => 'setFiles',
        'credit_status' => 'setCreditStatus',
        'promo_code' => 'setPromoCode',
        'refund_status' => 'setRefundStatus',
        'synced' => 'setSynced',
        'invoice_id' => 'setInvoiceId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'title' => 'getTitle',
        'status' => 'getStatus',
        'total' => 'getTotal',
        'contact' => 'getContact',
        'notes' => 'getNotes',
        'terms' => 'getTerms',
        'order_type' => 'getOrderType',
        'source_type' => 'getSourceType',
        'creation_time' => 'getCreationTime',
        'modification_time' => 'getModificationTime',
        'order_time' => 'getOrderTime',
        'lead_affiliate_id' => 'getLeadAffiliateId',
        'sales_affiliate_id' => 'getSalesAffiliateId',
        'total_paid' => 'getTotalPaid',
        'total_due' => 'getTotalDue',
        'shipping_information' => 'getShippingInformation',
        'refund_total' => 'getRefundTotal',
        'allow_payment' => 'getAllowPayment',
        'allow_paypal' => 'getAllowPaypal',
        'order_items' => 'getOrderItems',
        'payment_plan' => 'getPaymentPlan',
        'invoice_number' => 'getInvoiceNumber',
        'files' => 'getFiles',
        'credit_status' => 'getCreditStatus',
        'promo_code' => 'getPromoCode',
        'refund_status' => 'getRefundStatus',
        'synced' => 'getSynced',
        'invoice_id' => 'getInvoiceId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const STATUS_DRAFT = 'DRAFT';
    public const STATUS_SENT = 'SENT';
    public const STATUS_VIEWED = 'VIEWED';
    public const STATUS_PAID = 'PAID';
    public const ORDER_TYPE_ONLINE = 'ONLINE';
    public const ORDER_TYPE_OFFLINE = 'OFFLINE';
    public const SOURCE_TYPE_API = 'API';
    public const SOURCE_TYPE_CHECKOUT_FORM = 'CHECKOUT_FORM';
    public const SOURCE_TYPE_INVOICE = 'INVOICE';
    public const SOURCE_TYPE_MANUAL_PAYMENT = 'MANUAL_PAYMENT';
    public const SOURCE_TYPE_QUICKBOOKS = 'QUICKBOOKS';
    public const SOURCE_TYPE_UNKNOWN = 'UNKNOWN';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getStatusAllowableValues()
    {
        return [
            self::STATUS_DRAFT,
            self::STATUS_SENT,
            self::STATUS_VIEWED,
            self::STATUS_PAID,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getOrderTypeAllowableValues()
    {
        return [
            self::ORDER_TYPE_ONLINE,
            self::ORDER_TYPE_OFFLINE,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getSourceTypeAllowableValues()
    {
        return [
            self::SOURCE_TYPE_API,
            self::SOURCE_TYPE_CHECKOUT_FORM,
            self::SOURCE_TYPE_INVOICE,
            self::SOURCE_TYPE_MANUAL_PAYMENT,
            self::SOURCE_TYPE_QUICKBOOKS,
            self::SOURCE_TYPE_UNKNOWN,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('title', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('total', $data ?? [], null);
        $this->setIfExists('contact', $data ?? [], null);
        $this->setIfExists('notes', $data ?? [], null);
        $this->setIfExists('terms', $data ?? [], null);
        $this->setIfExists('order_type', $data ?? [], null);
        $this->setIfExists('source_type', $data ?? [], null);
        $this->setIfExists('creation_time', $data ?? [], null);
        $this->setIfExists('modification_time', $data ?? [], null);
        $this->setIfExists('order_time', $data ?? [], null);
        $this->setIfExists('lead_affiliate_id', $data ?? [], null);
        $this->setIfExists('sales_affiliate_id', $data ?? [], null);
        $this->setIfExists('total_paid', $data ?? [], null);
        $this->setIfExists('total_due', $data ?? [], null);
        $this->setIfExists('shipping_information', $data ?? [], null);
        $this->setIfExists('refund_total', $data ?? [], null);
        $this->setIfExists('allow_payment', $data ?? [], null);
        $this->setIfExists('allow_paypal', $data ?? [], null);
        $this->setIfExists('order_items', $data ?? [], null);
        $this->setIfExists('payment_plan', $data ?? [], null);
        $this->setIfExists('invoice_number', $data ?? [], null);
        $this->setIfExists('files', $data ?? [], null);
        $this->setIfExists('credit_status', $data ?? [], null);
        $this->setIfExists('promo_code', $data ?? [], null);
        $this->setIfExists('refund_status', $data ?? [], null);
        $this->setIfExists('synced', $data ?? [], null);
        $this->setIfExists('invoice_id', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getStatusAllowableValues();
        if (!is_null($this->container['status']) && !in_array($this->container['status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'status', must be one of '%s'",
                $this->container['status'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getOrderTypeAllowableValues();
        if (!is_null($this->container['order_type']) && !in_array($this->container['order_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'order_type', must be one of '%s'",
                $this->container['order_type'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getSourceTypeAllowableValues();
        if (!is_null($this->container['source_type']) && !in_array($this->container['source_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'source_type', must be one of '%s'",
                $this->container['source_type'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id Unique identifier for the order
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets title
     *
     * @return string|null
     */
    public function getTitle()
    {
        return $this->container['title'];
    }

    /**
     * Sets title
     *
     * @param string|null $title Title of the order
     *
     * @return self
     */
    public function setTitle($title)
    {
        if (is_null($title)) {
            throw new \InvalidArgumentException('non-nullable title cannot be null');
        }
        $this->container['title'] = $title;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string|null $status The order status.
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $allowedValues = $this->getStatusAllowableValues();
        if (!in_array($status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'status', must be one of '%s'",
                    $status,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets total
     *
     * @return \Keap\Core\V2\Model\CurrencyValue|null
     */
    public function getTotal()
    {
        return $this->container['total'];
    }

    /**
     * Sets total
     *
     * @param \Keap\Core\V2\Model\CurrencyValue|null $total The total amount of the order.
     *
     * @return self
     */
    public function setTotal($total)
    {
        if (is_null($total)) {
            throw new \InvalidArgumentException('non-nullable total cannot be null');
        }
        $this->container['total'] = $total;

        return $this;
    }

    /**
     * Gets contact
     *
     * @return \Keap\Core\V2\Model\BasicContact|null
     */
    public function getContact()
    {
        return $this->container['contact'];
    }

    /**
     * Sets contact
     *
     * @param \Keap\Core\V2\Model\BasicContact|null $contact Contact associated with this order
     *
     * @return self
     */
    public function setContact($contact)
    {
        if (is_null($contact)) {
            throw new \InvalidArgumentException('non-nullable contact cannot be null');
        }
        $this->container['contact'] = $contact;

        return $this;
    }

    /**
     * Gets notes
     *
     * @return string|null
     */
    public function getNotes()
    {
        return $this->container['notes'];
    }

    /**
     * Sets notes
     *
     * @param string|null $notes Internal notes for the order
     *
     * @return self
     */
    public function setNotes($notes)
    {
        if (is_null($notes)) {
            throw new \InvalidArgumentException('non-nullable notes cannot be null');
        }
        $this->container['notes'] = $notes;

        return $this;
    }

    /**
     * Gets terms
     *
     * @return string|null
     */
    public function getTerms()
    {
        return $this->container['terms'];
    }

    /**
     * Sets terms
     *
     * @param string|null $terms Order terms and conditions
     *
     * @return self
     */
    public function setTerms($terms)
    {
        if (is_null($terms)) {
            throw new \InvalidArgumentException('non-nullable terms cannot be null');
        }
        $this->container['terms'] = $terms;

        return $this;
    }

    /**
     * Gets order_type
     *
     * @return string|null
     */
    public function getOrderType()
    {
        return $this->container['order_type'];
    }

    /**
     * Sets order_type
     *
     * @param string|null $order_type The order type.
     *
     * @return self
     */
    public function setOrderType($order_type)
    {
        if (is_null($order_type)) {
            throw new \InvalidArgumentException('non-nullable order_type cannot be null');
        }
        $allowedValues = $this->getOrderTypeAllowableValues();
        if (!in_array($order_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'order_type', must be one of '%s'",
                    $order_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['order_type'] = $order_type;

        return $this;
    }

    /**
     * Gets source_type
     *
     * @return string|null
     */
    public function getSourceType()
    {
        return $this->container['source_type'];
    }

    /**
     * Sets source_type
     *
     * @param string|null $source_type The source where the order was created.
     *
     * @return self
     */
    public function setSourceType($source_type)
    {
        if (is_null($source_type)) {
            throw new \InvalidArgumentException('non-nullable source_type cannot be null');
        }
        $allowedValues = $this->getSourceTypeAllowableValues();
        if (!in_array($source_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'source_type', must be one of '%s'",
                    $source_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['source_type'] = $source_type;

        return $this;
    }

    /**
     * Gets creation_time
     *
     * @return \DateTime|null
     */
    public function getCreationTime()
    {
        return $this->container['creation_time'];
    }

    /**
     * Sets creation_time
     *
     * @param \DateTime|null $creation_time When this order was originally created. In ISO-8601 format (e.g. 2024-05-21T23:00:00Z)
     *
     * @return self
     */
    public function setCreationTime($creation_time)
    {
        if (is_null($creation_time)) {
            throw new \InvalidArgumentException('non-nullable creation_time cannot be null');
        }
        $this->container['creation_time'] = $creation_time;

        return $this;
    }

    /**
     * Gets modification_time
     *
     * @return \DateTime|null
     */
    public function getModificationTime()
    {
        return $this->container['modification_time'];
    }

    /**
     * Sets modification_time
     *
     * @param \DateTime|null $modification_time When this order was changed. In ISO-8601 format (e.g. 2024-05-21T23:00:00Z)
     *
     * @return self
     */
    public function setModificationTime($modification_time)
    {
        if (is_null($modification_time)) {
            throw new \InvalidArgumentException('non-nullable modification_time cannot be null');
        }
        $this->container['modification_time'] = $modification_time;

        return $this;
    }

    /**
     * Gets order_time
     *
     * @return \DateTime|null
     */
    public function getOrderTime()
    {
        return $this->container['order_time'];
    }

    /**
     * Sets order_time
     *
     * @param \DateTime|null $order_time A user-defined date and time of the order. In ISO-8601 format (e.g. 2024-05-21T23:00:00Z)
     *
     * @return self
     */
    public function setOrderTime($order_time)
    {
        if (is_null($order_time)) {
            throw new \InvalidArgumentException('non-nullable order_time cannot be null');
        }
        $this->container['order_time'] = $order_time;

        return $this;
    }

    /**
     * Gets lead_affiliate_id
     *
     * @return string|null
     */
    public function getLeadAffiliateId()
    {
        return $this->container['lead_affiliate_id'];
    }

    /**
     * Sets lead_affiliate_id
     *
     * @param string|null $lead_affiliate_id ID of the lead affiliate
     *
     * @return self
     */
    public function setLeadAffiliateId($lead_affiliate_id)
    {
        if (is_null($lead_affiliate_id)) {
            throw new \InvalidArgumentException('non-nullable lead_affiliate_id cannot be null');
        }
        $this->container['lead_affiliate_id'] = $lead_affiliate_id;

        return $this;
    }

    /**
     * Gets sales_affiliate_id
     *
     * @return string|null
     */
    public function getSalesAffiliateId()
    {
        return $this->container['sales_affiliate_id'];
    }

    /**
     * Sets sales_affiliate_id
     *
     * @param string|null $sales_affiliate_id ID of the sales affiliate
     *
     * @return self
     */
    public function setSalesAffiliateId($sales_affiliate_id)
    {
        if (is_null($sales_affiliate_id)) {
            throw new \InvalidArgumentException('non-nullable sales_affiliate_id cannot be null');
        }
        $this->container['sales_affiliate_id'] = $sales_affiliate_id;

        return $this;
    }

    /**
     * Gets total_paid
     *
     * @return \Keap\Core\V2\Model\CurrencyValue|null
     */
    public function getTotalPaid()
    {
        return $this->container['total_paid'];
    }

    /**
     * Sets total_paid
     *
     * @param \Keap\Core\V2\Model\CurrencyValue|null $total_paid The total amount paid to the order.
     *
     * @return self
     */
    public function setTotalPaid($total_paid)
    {
        if (is_null($total_paid)) {
            throw new \InvalidArgumentException('non-nullable total_paid cannot be null');
        }
        $this->container['total_paid'] = $total_paid;

        return $this;
    }

    /**
     * Gets total_due
     *
     * @return \Keap\Core\V2\Model\CurrencyValue|null
     */
    public function getTotalDue()
    {
        return $this->container['total_due'];
    }

    /**
     * Sets total_due
     *
     * @param \Keap\Core\V2\Model\CurrencyValue|null $total_due The total amount of the order that is due. This is not current balance.
     *
     * @return self
     */
    public function setTotalDue($total_due)
    {
        if (is_null($total_due)) {
            throw new \InvalidArgumentException('non-nullable total_due cannot be null');
        }
        $this->container['total_due'] = $total_due;

        return $this;
    }

    /**
     * Gets shipping_information
     *
     * @return \Keap\Core\V2\Model\ShippingInformation|null
     */
    public function getShippingInformation()
    {
        return $this->container['shipping_information'];
    }

    /**
     * Sets shipping_information
     *
     * @param \Keap\Core\V2\Model\ShippingInformation|null $shipping_information Shipping details for the order
     *
     * @return self
     */
    public function setShippingInformation($shipping_information)
    {
        if (is_null($shipping_information)) {
            throw new \InvalidArgumentException('non-nullable shipping_information cannot be null');
        }
        $this->container['shipping_information'] = $shipping_information;

        return $this;
    }

    /**
     * Gets refund_total
     *
     * @return \Keap\Core\V2\Model\CurrencyValue|null
     */
    public function getRefundTotal()
    {
        return $this->container['refund_total'];
    }

    /**
     * Sets refund_total
     *
     * @param \Keap\Core\V2\Model\CurrencyValue|null $refund_total Total amount refunded
     *
     * @return self
     */
    public function setRefundTotal($refund_total)
    {
        if (is_null($refund_total)) {
            throw new \InvalidArgumentException('non-nullable refund_total cannot be null');
        }
        $this->container['refund_total'] = $refund_total;

        return $this;
    }

    /**
     * Gets allow_payment
     *
     * @return bool|null
     */
    public function getAllowPayment()
    {
        return $this->container['allow_payment'];
    }

    /**
     * Sets allow_payment
     *
     * @param bool|null $allow_payment Whether or not card-related payments should be allowed on this order. Applies only to Keap Pro/Max edition.
     *
     * @return self
     */
    public function setAllowPayment($allow_payment)
    {
        if (is_null($allow_payment)) {
            throw new \InvalidArgumentException('non-nullable allow_payment cannot be null');
        }
        $this->container['allow_payment'] = $allow_payment;

        return $this;
    }

    /**
     * Gets allow_paypal
     *
     * @return bool|null
     */
    public function getAllowPaypal()
    {
        return $this->container['allow_paypal'];
    }

    /**
     * Sets allow_paypal
     *
     * @param bool|null $allow_paypal Whether or not PayPal payments should be allowed on this order. Applies only to Keap Pro/Max edition.
     *
     * @return self
     */
    public function setAllowPaypal($allow_paypal)
    {
        if (is_null($allow_paypal)) {
            throw new \InvalidArgumentException('non-nullable allow_paypal cannot be null');
        }
        $this->container['allow_paypal'] = $allow_paypal;

        return $this;
    }

    /**
     * Gets order_items
     *
     * @return \Keap\Core\V2\Model\OrderItem[]|null
     */
    public function getOrderItems()
    {
        return $this->container['order_items'];
    }

    /**
     * Sets order_items
     *
     * @param \Keap\Core\V2\Model\OrderItem[]|null $order_items List of items in the order
     *
     * @return self
     */
    public function setOrderItems($order_items)
    {
        if (is_null($order_items)) {
            throw new \InvalidArgumentException('non-nullable order_items cannot be null');
        }
        $this->container['order_items'] = $order_items;

        return $this;
    }

    /**
     * Gets payment_plan
     *
     * @return \Keap\Core\V2\Model\PaymentPlan|null
     */
    public function getPaymentPlan()
    {
        return $this->container['payment_plan'];
    }

    /**
     * Sets payment_plan
     *
     * @param \Keap\Core\V2\Model\PaymentPlan|null $payment_plan Payment plan details if applicable
     *
     * @return self
     */
    public function setPaymentPlan($payment_plan)
    {
        if (is_null($payment_plan)) {
            throw new \InvalidArgumentException('non-nullable payment_plan cannot be null');
        }
        $this->container['payment_plan'] = $payment_plan;

        return $this;
    }

    /**
     * Gets invoice_number
     *
     * @return string|null
     */
    public function getInvoiceNumber()
    {
        return $this->container['invoice_number'];
    }

    /**
     * Sets invoice_number
     *
     * @param string|null $invoice_number The associated invoice identifier. Applies only to Keap Pro/Max edition. Feature not yet supported.
     *
     * @return self
     */
    public function setInvoiceNumber($invoice_number)
    {
        if (is_null($invoice_number)) {
            throw new \InvalidArgumentException('non-nullable invoice_number cannot be null');
        }
        $this->container['invoice_number'] = $invoice_number;

        return $this;
    }

    /**
     * Gets files
     *
     * @return \Keap\Core\V2\Model\InvoiceFile[]|null
     */
    public function getFiles()
    {
        return $this->container['files'];
    }

    /**
     * Sets files
     *
     * @param \Keap\Core\V2\Model\InvoiceFile[]|null $files A list of attached files to this order. Applies only to Keap Pro/Max edition.
     *
     * @return self
     */
    public function setFiles($files)
    {
        if (is_null($files)) {
            throw new \InvalidArgumentException('non-nullable files cannot be null');
        }
        $this->container['files'] = $files;

        return $this;
    }

    /**
     * Gets credit_status
     *
     * @return string|null
     */
    public function getCreditStatus()
    {
        return $this->container['credit_status'];
    }

    /**
     * Sets credit_status
     *
     * @param string|null $credit_status Credit status of the order
     *
     * @return self
     */
    public function setCreditStatus($credit_status)
    {
        if (is_null($credit_status)) {
            throw new \InvalidArgumentException('non-nullable credit_status cannot be null');
        }
        $this->container['credit_status'] = $credit_status;

        return $this;
    }

    /**
     * Gets promo_code
     *
     * @return string|null
     */
    public function getPromoCode()
    {
        return $this->container['promo_code'];
    }

    /**
     * Sets promo_code
     *
     * @param string|null $promo_code Promotional code applied
     *
     * @return self
     */
    public function setPromoCode($promo_code)
    {
        if (is_null($promo_code)) {
            throw new \InvalidArgumentException('non-nullable promo_code cannot be null');
        }
        $this->container['promo_code'] = $promo_code;

        return $this;
    }

    /**
     * Gets refund_status
     *
     * @return string|null
     */
    public function getRefundStatus()
    {
        return $this->container['refund_status'];
    }

    /**
     * Sets refund_status
     *
     * @param string|null $refund_status Refund status
     *
     * @return self
     */
    public function setRefundStatus($refund_status)
    {
        if (is_null($refund_status)) {
            throw new \InvalidArgumentException('non-nullable refund_status cannot be null');
        }
        $this->container['refund_status'] = $refund_status;

        return $this;
    }

    /**
     * Gets synced
     *
     * @return bool|null
     */
    public function getSynced()
    {
        return $this->container['synced'];
    }

    /**
     * Sets synced
     *
     * @param bool|null $synced Whether order is synced with external systems
     *
     * @return self
     */
    public function setSynced($synced)
    {
        if (is_null($synced)) {
            throw new \InvalidArgumentException('non-nullable synced cannot be null');
        }
        $this->container['synced'] = $synced;

        return $this;
    }

    /**
     * Gets invoice_id
     *
     * @return string|null
     */
    public function getInvoiceId()
    {
        return $this->container['invoice_id'];
    }

    /**
     * Sets invoice_id
     *
     * @param string|null $invoice_id Associated invoice ID
     *
     * @return self
     */
    public function setInvoiceId($invoice_id)
    {
        if (is_null($invoice_id)) {
            throw new \InvalidArgumentException('non-nullable invoice_id cannot be null');
        }
        $this->container['invoice_id'] = $invoice_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


