<?php
/**
 * PipelineCustomFieldDisplayStyle
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Keap\Core\V2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Keap REST API
 *
 * Keap REST Core Service
 *
 * The version of the OpenAPI document: 2.70.0.809589
 * Contact: api@keap.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Keap\Core\V2\Model;
use \Keap\Core\V2\ObjectSerializer;

/**
 * PipelineCustomFieldDisplayStyle Class Doc Comment
 *
 * @category Class
 * @description Enum representing the display styles for custom fields.
 * @package  Keap\Core\V2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PipelineCustomFieldDisplayStyle
{
    /**
     * Possible values of this enum
     */
    public const QUOTE = 'QUOTE';

    public const BOLD = 'BOLD';

    public const ALIGN_END = 'ALIGN_END';

    public const ITALIC = 'ITALIC';

    public const LARGE = 'LARGE';

    public const MEDIUM = 'MEDIUM';

    public const SMALL = 'SMALL';

    public const XS = 'XS';

    public const CENTER = 'CENTER';

    public const HYPHENATED = 'HYPHENATED';

    public const LABELED = 'LABELED';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::QUOTE,
            self::BOLD,
            self::ALIGN_END,
            self::ITALIC,
            self::LARGE,
            self::MEDIUM,
            self::SMALL,
            self::XS,
            self::CENTER,
            self::HYPHENATED,
            self::LABELED
        ];
    }
}


