<?php
/**
 * RestAffiliate
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Keap\Core\V2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Keap API
 *
 * Keap Public API Documentation
 *
 * The version of the OpenAPI document: v2
 * Contact: api.keap@thryv.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Keap\Core\V2\Model;

use \ArrayAccess;
use \Keap\Core\V2\ObjectSerializer;

/**
 * RestAffiliate Class Doc Comment
 *
 * @category Class
 * @package  Keap\Core\V2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class RestAffiliate implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'RestAffiliate';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'code' => 'string',
        'name' => 'string',
        'status' => 'string',
        'contact_id' => 'string',
        'unique_site_id' => 'string',
        'date_created' => 'string',
        'parent_affiliate_id' => 'string',
        'notify_on_sale' => 'bool',
        'notify_on_lead' => 'bool',
        'track_leads_days' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'code' => null,
        'name' => null,
        'status' => null,
        'contact_id' => null,
        'unique_site_id' => null,
        'date_created' => null,
        'parent_affiliate_id' => null,
        'notify_on_sale' => null,
        'notify_on_lead' => null,
        'track_leads_days' => 'int32'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'code' => false,
        'name' => false,
        'status' => false,
        'contact_id' => false,
        'unique_site_id' => false,
        'date_created' => false,
        'parent_affiliate_id' => false,
        'notify_on_sale' => false,
        'notify_on_lead' => false,
        'track_leads_days' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'code' => 'code',
        'name' => 'name',
        'status' => 'status',
        'contact_id' => 'contact_id',
        'unique_site_id' => 'unique_site_id',
        'date_created' => 'date_created',
        'parent_affiliate_id' => 'parent_affiliate_id',
        'notify_on_sale' => 'notify_on_sale',
        'notify_on_lead' => 'notify_on_lead',
        'track_leads_days' => 'track_leads_days'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'code' => 'setCode',
        'name' => 'setName',
        'status' => 'setStatus',
        'contact_id' => 'setContactId',
        'unique_site_id' => 'setUniqueSiteId',
        'date_created' => 'setDateCreated',
        'parent_affiliate_id' => 'setParentAffiliateId',
        'notify_on_sale' => 'setNotifyOnSale',
        'notify_on_lead' => 'setNotifyOnLead',
        'track_leads_days' => 'setTrackLeadsDays'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'code' => 'getCode',
        'name' => 'getName',
        'status' => 'getStatus',
        'contact_id' => 'getContactId',
        'unique_site_id' => 'getUniqueSiteId',
        'date_created' => 'getDateCreated',
        'parent_affiliate_id' => 'getParentAffiliateId',
        'notify_on_sale' => 'getNotifyOnSale',
        'notify_on_lead' => 'getNotifyOnLead',
        'track_leads_days' => 'getTrackLeadsDays'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const STATUS_ACTIVE = 'ACTIVE';
    public const STATUS_INACTIVE = 'INACTIVE';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getStatusAllowableValues()
    {
        return [
            self::STATUS_ACTIVE,
            self::STATUS_INACTIVE,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('code', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('contact_id', $data ?? [], null);
        $this->setIfExists('unique_site_id', $data ?? [], null);
        $this->setIfExists('date_created', $data ?? [], null);
        $this->setIfExists('parent_affiliate_id', $data ?? [], null);
        $this->setIfExists('notify_on_sale', $data ?? [], null);
        $this->setIfExists('notify_on_lead', $data ?? [], null);
        $this->setIfExists('track_leads_days', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getStatusAllowableValues();
        if (!is_null($this->container['status']) && !in_array($this->container['status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'status', must be one of '%s'",
                $this->container['status'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id The AffiliateId
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets code
     *
     * @return string|null
     */
    public function getCode()
    {
        return $this->container['code'];
    }

    /**
     * Sets code
     *
     * @param string|null $code The Affiliate Code
     *
     * @return self
     */
    public function setCode($code)
    {
        if (is_null($code)) {
            throw new \InvalidArgumentException('non-nullable code cannot be null');
        }
        $this->container['code'] = $code;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name The Affiliate Name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string|null $status The Affiliate Status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $allowedValues = $this->getStatusAllowableValues();
        if (!in_array($status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'status', must be one of '%s'",
                    $status,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets contact_id
     *
     * @return string|null
     */
    public function getContactId()
    {
        return $this->container['contact_id'];
    }

    /**
     * Sets contact_id
     *
     * @param string|null $contact_id The ContactID
     *
     * @return self
     */
    public function setContactId($contact_id)
    {
        if (is_null($contact_id)) {
            throw new \InvalidArgumentException('non-nullable contact_id cannot be null');
        }
        $this->container['contact_id'] = $contact_id;

        return $this;
    }

    /**
     * Gets unique_site_id
     *
     * @return string|null
     */
    public function getUniqueSiteId()
    {
        return $this->container['unique_site_id'];
    }

    /**
     * Sets unique_site_id
     *
     * @param string|null $unique_site_id The Affiliate PortalSite Id
     *
     * @return self
     */
    public function setUniqueSiteId($unique_site_id)
    {
        if (is_null($unique_site_id)) {
            throw new \InvalidArgumentException('non-nullable unique_site_id cannot be null');
        }
        $this->container['unique_site_id'] = $unique_site_id;

        return $this;
    }

    /**
     * Gets date_created
     *
     * @return string|null
     */
    public function getDateCreated()
    {
        return $this->container['date_created'];
    }

    /**
     * Sets date_created
     *
     * @param string|null $date_created Date affiliate was created (ISO-8601)
     *
     * @return self
     */
    public function setDateCreated($date_created)
    {
        if (is_null($date_created)) {
            throw new \InvalidArgumentException('non-nullable date_created cannot be null');
        }
        $this->container['date_created'] = $date_created;

        return $this;
    }

    /**
     * Gets parent_affiliate_id
     *
     * @return string|null
     */
    public function getParentAffiliateId()
    {
        return $this->container['parent_affiliate_id'];
    }

    /**
     * Sets parent_affiliate_id
     *
     * @param string|null $parent_affiliate_id The Parent Affiliate Id
     *
     * @return self
     */
    public function setParentAffiliateId($parent_affiliate_id)
    {
        if (is_null($parent_affiliate_id)) {
            throw new \InvalidArgumentException('non-nullable parent_affiliate_id cannot be null');
        }
        $this->container['parent_affiliate_id'] = $parent_affiliate_id;

        return $this;
    }

    /**
     * Gets notify_on_sale
     *
     * @return bool|null
     */
    public function getNotifyOnSale()
    {
        return $this->container['notify_on_sale'];
    }

    /**
     * Sets notify_on_sale
     *
     * @param bool|null $notify_on_sale Whether to notify on sale events
     *
     * @return self
     */
    public function setNotifyOnSale($notify_on_sale)
    {
        if (is_null($notify_on_sale)) {
            throw new \InvalidArgumentException('non-nullable notify_on_sale cannot be null');
        }
        $this->container['notify_on_sale'] = $notify_on_sale;

        return $this;
    }

    /**
     * Gets notify_on_lead
     *
     * @return bool|null
     */
    public function getNotifyOnLead()
    {
        return $this->container['notify_on_lead'];
    }

    /**
     * Sets notify_on_lead
     *
     * @param bool|null $notify_on_lead Whether to notify on lead events
     *
     * @return self
     */
    public function setNotifyOnLead($notify_on_lead)
    {
        if (is_null($notify_on_lead)) {
            throw new \InvalidArgumentException('non-nullable notify_on_lead cannot be null');
        }
        $this->container['notify_on_lead'] = $notify_on_lead;

        return $this;
    }

    /**
     * Gets track_leads_days
     *
     * @return int|null
     */
    public function getTrackLeadsDays()
    {
        return $this->container['track_leads_days'];
    }

    /**
     * Sets track_leads_days
     *
     * @param int|null $track_leads_days Number of days to track leads
     *
     * @return self
     */
    public function setTrackLeadsDays($track_leads_days)
    {
        if (is_null($track_leads_days)) {
            throw new \InvalidArgumentException('non-nullable track_leads_days cannot be null');
        }
        $this->container['track_leads_days'] = $track_leads_days;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


